---
title: "WAP2 Eggs Morphometrics"
author: "Adriane McDonald"
date: '2022-08-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
```

## Import dataset

```{r}
egg2_data <- read_csv("~/Desktop/WAP_data_2022/eggs_morphs_2_wap.csv")
```

### Exploratory data visualization

Exploratory histograms: 

```{r}
ggplot(egg2_data, aes(x = Area)) +
  geom_histogram(bins = 15) +
  facet_wrap(~Treatment)

ggplot(egg2_data, aes(x= Diameter)) +
  geom_histogram(bins = 15) +
  facet_wrap(~Treatment)

```

### Quantile-quantile

```{r}
ggplot(egg2_data, aes(sample = Area))+
  geom_qq()+
  facet_wrap(~Treatment)

ggplot(egg2_data, aes(sample = Diameter))+
  geom_qq()+
  facet_wrap(~Treatment)
```

### Descriptive Statistics 

```{r}
#AREA
egg2_area_stats <- egg2_data %>%
  group_by(Treatment) %>%
  summarize(mean_area = mean(Area),
            sd_area = sd(Area),
            n = n())
egg2_area_stats

#generating a table

egg2_area_stats %>%
  kbl(col.names = c("Treatment", "Mean", "Standard Deviation", "Sample Size"),
      align = 'c') %>%
  kable_classic(full_width = F, html_font = "Cambria")

#DIAMETER
egg2_diameter_stats <- egg2_data %>%
  group_by(Treatment) %>%
  summarize(mean_diameter = mean(Diameter),
            sd_area = sd(Diameter),
            n = n())
egg2_diameter_stats

#generating a table

egg2_diameter_stats %>%
  kbl(col.names = c("Treatment", "Mean", "Standard Deviation", "Sample Size"),
      align = 'c') %>%
  kable_classic(full_width = F, html_font = "Cambria")

egg2_diameter_stats

```


### 2-sample t-test for Area

```{r}
hot_sample <- egg2_data %>%
  filter(Treatment == "Hot") %>%
  pull(Area)

ambient_sample <- egg2_data %>%
  filter(Treatment == "Ambient") %>%
  pull(Area)

t.test(x = hot_sample, ambient_sample)
```

### 2-sample t-test for Diameter

```{r}
hot_sample_diameter <- egg2_data %>%
  filter(Treatment == "Hot") %>%
  pull(Diameter)

ambient_sample_diameter <- egg2_data %>%
  filter(Treatment == "Ambient") %>%
  pull(Diameter)

t.test(x = hot_sample_diameter, ambient_sample_diameter)
```


### Creating a box plot for Egg diameter

```{r}
ggplot(egg2_data, aes(x = Treatment, y = Diameter, fill = Treatment)) +
  geom_boxplot(outlier.colour = "black", outlier.shape = 1)+
  theme_classic()+
  xlab("Adult Treatment") +
  ylab("Egg Diameter (mm)") +
  scale_fill_manual(values = c("#3399CC","#CC0000"))+
  annotate(geom = "text", x= 2.3, y = 0.025, label = " p < 0.001",
           size = 4)
  
  
```

### Creating a box plot for Egg Area

```{r}

ggplot(egg2_data, aes(x = Treatment, y = Area, fill = Treatment)) +
  geom_boxplot(outlier.colour = "black", outlier.shape = 1)+
  theme_classic()+
  xlab("Adult Treatment") +
  ylab(bquote('Egg Area (' ~mm^2 ~')'))+
  scale_fill_manual(values = c("#3399CC","#CC0000"))+
  annotate(geom = "text", x= 2.3, y = 0.00025, label = " p < 0.01",
           size = 4)+
  ylim(0,0.015)
  
```

